#!/usr/bin/env bash

# Immutable PVM and Xolis build inputs. Keep this file declarative so both the
# artifact builder and the AMI builder consume the same provenance.
PVM_SOURCE_URL="https://github.com/virt-pvm/linux.git"
PVM_SOURCE_COMMIT="91e9c9be4472756890844b2c982d7c72252dbfe6"
PVM_KERNEL_VERSION="6.12.33"

PVM_MISC_COMMIT="13b60b1030bf40d025e229a6c58ba224be30acbf"
PVM_GUEST_CONFIG_URL="https://raw.githubusercontent.com/virt-pvm/misc/${PVM_MISC_COMMIT}/pvm-guest-6.12.33.config"
PVM_GUEST_CONFIG_SHA256="a17d877e5117288a762bcbeda3825ea5d85c63c8542752273ec2dc2c66f9609b"

EKS_KUBERNETES_VERSION="1.35"
EKS_AMI_RELEASE_VERSION="1.35.6-20260728"
EKS_AMI_RELEASE_TAG="v20260728"
EKS_SOURCE_AMI_REGION="ap-northeast-1"
EKS_SOURCE_AMI_ID="ami-0f15c654d8131cadd"
EKS_SOURCE_AMI_NAME="amazon-eks-node-al2023-x86_64-standard-1.35-v20260728"
EKS_REFERENCE_KERNEL_VERSION="6.12.94-123.192.amzn2023"

# SHA-256 of /boot/config-6.12.94-123.192.amzn2023.x86_64 from the pinned AMI.
EKS_HOST_CONFIG_SHA256="701a459dda4c3bfecb322eea5c465d071b0f21e1101839a5e3637f43e207dad6"

KATA_VERSION="4.0.0"
KATA_SOURCE_COMMIT="cf82bb35c80320178bf7570252fe75d6fb263209"
RUST_TOOLCHAIN_VERSION="1.95"

PVM_HOST_REQUIRED_CMDLINE="pti=off"

# Published artifact identities for the first validated PVM host/runtime set.
# The bucket is deployment-specific and is supplied to the AMI build; these
# digests make the selected objects immutable and independently verifiable.
PVM_KERNEL_MANIFEST_SHA256="61f63839c192ee1eb61bd9abde40584ed352ac05f06e4392cf489ede6fdc15df"
PVM_RUNTIME_MANIFEST_SHA256="6b624dff525e1a126ba91ca30decc49bdae7f59ae3fd81d196efa4e819e33ca5"
PVM_RUNTIME_ARCHIVE_SHA256="ca4781bea4684834c6dda05f8b030795114b7be48868e210b6149944376b538b"

# The build manifest is generated by a child Python process. Export the pinned
# values so the shell build and manifest generator consume identical inputs.
export PVM_SOURCE_URL PVM_SOURCE_COMMIT PVM_KERNEL_VERSION
export PVM_MISC_COMMIT PVM_GUEST_CONFIG_URL PVM_GUEST_CONFIG_SHA256
export EKS_KUBERNETES_VERSION EKS_AMI_RELEASE_VERSION EKS_AMI_RELEASE_TAG
export EKS_SOURCE_AMI_REGION EKS_SOURCE_AMI_ID EKS_SOURCE_AMI_NAME
export EKS_REFERENCE_KERNEL_VERSION EKS_HOST_CONFIG_SHA256
export KATA_VERSION KATA_SOURCE_COMMIT RUST_TOOLCHAIN_VERSION
export PVM_HOST_REQUIRED_CMDLINE
export PVM_KERNEL_MANIFEST_SHA256 PVM_RUNTIME_MANIFEST_SHA256
export PVM_RUNTIME_ARCHIVE_SHA256
