version = 1
root = "/var/lib/containerd/io.containerd.snapshotter.v1.nydus"
address = "/run/containerd-nydus/containerd-nydus-grpc.sock"
daemon_mode = "dedicated"
cleanup_on_close = true

[daemon]
nydusd_config = "/etc/nydus/nydusd-config.fusedev.json"
nydusd_path = "/usr/local/bin/nydusd"
nydusimage_path = "/usr/local/bin/nydus-image"
fs_driver = "fusedev"
recover_policy = "restart"
threads_number = 4

[remote]
convert_vpc_registry = false

[remote.auth]
enable_kubelet_credential_providers = true
credential_provider_config = "/etc/nydus/ecr-credential-provider-config.json"
credential_provider_bin_dir = "/etc/eks/image-credential-provider"
credential_renewal_interval = "4h"

[snapshot]
enable_kata_volume = true
sync_remove = true
