apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap/xolis-runtime.yaml
  - xolis/namespaces.yaml
  - xolis/api-rbac.yaml
  - xolis/api.yaml
  - xolis/router-rbac.yaml
  - xolis/router.yaml
  - xolis/python-profile.yaml
  - xolis/network-policies.yaml
